services:
  reverse_proxy:
    image: local/caddy
    ports:
      - 443:443
      - 80:80
    build:
      context: caddy
      dockerfile: Dockerfile
    pull_policy: never
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - reverse_proxy

  watchtower:
    image: nickfedor/watchtower
    environment:
      - DOCKER_CONFIG=${DOCKER_CONFIG_PATH}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - docker-config:${DOCKER_CONFIG_PATH}
    command:
      - "--label-enable"
      - "--interval"
      - "30"
    restart: unless-stopped

  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    ports:
      - 3001:3001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - uptime-kuma:/app/data
    restart: unless-stopped

  alpine-cron:
    image: local/alpine-cron
    build:
      context: alpine-cron
      dockerfile: Dockerfile
    pull_policy: never
    restart: unless-stopped
    environment:
      - DOCKER_CONFIG=${DOCKER_CONFIG_PATH}
    volumes:
      - aws-credentials:/root/.aws
      - docker-config:${DOCKER_CONFIG_PATH}
      - alpine-cron-logs:/var/log
    env_file:
      - ./alpine-cron/.env

  portfolio:
    image: ${PORTFOLIO_IMAGE_NAME}
    restart: unless-stopped
    env_file:
      - ./portfolio/nextjs/.env
    labels:
      - com.centurylinklabs.watchtower.enable=true
    volumes:
      - ./portfolio/nextjs/prod-ca-2021.crt:/app/prod-ca-2021.crt
    networks:
      - reverse_proxy
      - portfolio

  portfolio-cron-jobs:
    image: ${PORTFOLIO_CRON_JOBS_IMAGE_NAME}
    restart: unless-stopped
    env_file:
      - ./portfolio/cron-jobs/.env
    labels:
      - com.centurylinklabs.watchtower.enable=true
    networks:
      - portfolio

  blog:
    image: ${BLOG_IMAGE_NAME}
    restart: unless-stopped
    env_file:
      - ./blog/nextjs/.env
    labels:
      - com.centurylinklabs.watchtower.enable=true
    networks:
      - reverse_proxy

  tori:
    image: ${TORI_IMAGE_NAME}
    restart: unless-stopped
    labels:
      - com.centurylinklabs.watchtower.enable=true
    networks:
      - reverse_proxy

volumes:
  uptime-kuma:
  aws-credentials:
  alpine-cron-logs:
  docker-config:
  caddy_data:
  caddy_config:

networks:
  portfolio:
  reverse_proxy:
